### ISSUE TITLE
Only download the HTML files

### ISSUE THREAD

**Issue by malteriechmann** [visuellverstehen/t3fetch#2]
Right now all files will be downloaded. This is not very performant and will take a lot of extra space for large websites.

We should only download the HTML files.

**Comment by runepiper** [comment]
Now specific file extensions are ignore ([see here](https://github.com/visuellverstehen/t3fetch/blob/adec9bde77c156109d84c602b85d4d125c7eb1a8/Classes/Command/FetchWebsiteCommand.php#L14)) and also downloaded files are deleted right after the download ([see here](https://github.com/visuellverstehen/t3fetch/commit/8f9bfb40cc2cece91a8e8f30cfa90be1b1e041be)).
