### ISSUE TITLE
wget oberloads website/CPU/apache while crawling

### ISSUE THREAD

**Issue by fgerards** [visuellverstehen/t3fetch#8]
there needs to be a throttling of the wget requests as without it you basically initiate a DDoS attack on your own webserver.

**Comment by runepiper** [comment]
Good point. I am thinking about adding a fixed `--limit-rate` parameter.

**Comment by runepiper** [comment]
I added an option called `--limit` which will be passed to wget's `--limit-rate` option. Please use version 1.3 to use this new option.
