### ISSUE TITLE
Fetch protected Websites

### ISSUE THREAD

**Issue by taunusweb** [visuellverstehen/t3fetch#9]
Hi there,

great extension for my purpose, because I run a Site which is filled by an API and the content isn't stored in the TYPO3 Database, but I have one question: is it possible to fetch Websites, which are protected by a login script? 

Thanks Uli

**Comment by malteriechmann** [comment]
Hi @taunusweb, great – thanks for your feedback.

Right now it is not possible to fetch protected websites.

Do you mean websites protected by HTTP basic authentication or websites with protected pages behind a HTML login form?

**Comment by taunusweb** [comment]
Protected Pages behind a login form...

**Comment by malteriechmann** [comment]
Okay. This will be not so easy to implement, because behind `t3fetch` is just a simple usage of `wget`.

Sorry. I think you need to check out other extensions, e. g. `crawler` (https://extensions.typo3.org/extension/crawler).
